/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { ConcordiaApiContext } from "./concordiaApiContext";

class ConcordiaApi extends ConcordiaApiContext {
  // Operation groups
  apiRestAuth: operations.ApiRestAuth;
  apiTokenAuth: operations.ApiTokenAuth;
  apiTokenRefresh: operations.ApiTokenRefresh;
  api: operations.Api;
  authJwtRefresh: operations.AuthJwtRefresh;
  authJwtVerify: operations.AuthJwtVerify;
  authJwt: operations.AuthJwt;
  person: operations.PersonOperations;
  register: operations.Register;
  rent: operations.RentOperations;
  service: operations.ServiceOperations;
  user: operations.UserOperations;

  /**
   * Initializes a new instance of the ConcordiaApi class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.ConcordiaApiOptions) {
    super(credentials, options);
    this.apiRestAuth = new operations.ApiRestAuth(this);
    this.apiTokenAuth = new operations.ApiTokenAuth(this);
    this.apiTokenRefresh = new operations.ApiTokenRefresh(this);
    this.api = new operations.Api(this);
    this.authJwtRefresh = new operations.AuthJwtRefresh(this);
    this.authJwtVerify = new operations.AuthJwtVerify(this);
    this.authJwt = new operations.AuthJwt(this);
    this.person = new operations.PersonOperations(this);
    this.register = new operations.Register(this);
    this.rent = new operations.RentOperations(this);
    this.service = new operations.ServiceOperations(this);
    this.user = new operations.UserOperations(this);
  }
}

// Operation Specifications

export {
  ConcordiaApi,
  ConcordiaApiContext,
  Models as ConcordiaApiModels,
  Mappers as ConcordiaApiMappers
};
export * from "./operations";
