/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";

export const id: msRest.OperationURLParameter = {
  parameterPath: "id",
  mapper: {
    required: true,
    serializedName: "id",
    type: {
      name: "Number"
    }
  }
};
export const user: msRest.OperationURLParameter = {
  parameterPath: "user",
  mapper: {
    required: true,
    serializedName: "user",
    type: {
      name: "String"
    }
  }
};
