/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/apiTokenAuthMappers";
import { ConcordiaApiContext } from "../concordiaApiContext";

/** Class representing a ApiTokenAuth. */
export class ApiTokenAuth {
  private readonly client: ConcordiaApiContext;

  /**
   * Create a ApiTokenAuth.
   * @param {ConcordiaApiContext} client Reference to the service client.
   */
  constructor(client: ConcordiaApiContext) {
    this.client = client;
  }

  /**
   * Returns a JSON Web Token that can be used for authenticated requests.
   * @summary API View that receives a POST with a user's username and password.
   * @param data
   * @param [options] The optional parameters
   * @returns Promise<Models.ApiTokenAuthCreateResponse>
   */
  create(data: Models.JSONWebToken, options?: msRest.RequestOptionsBase): Promise<Models.ApiTokenAuthCreateResponse>;
  /**
   * @param data
   * @param callback The callback
   */
  create(data: Models.JSONWebToken, callback: msRest.ServiceCallback<Models.JSONWebToken>): void;
  /**
   * @param data
   * @param options The optional parameters
   * @param callback The callback
   */
  create(data: Models.JSONWebToken, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.JSONWebToken>): void;
  create(data: Models.JSONWebToken, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.JSONWebToken>, callback?: msRest.ServiceCallback<Models.JSONWebToken>): Promise<Models.ApiTokenAuthCreateResponse> {
    return this.client.sendOperationRequest(
      {
        data,
        options
      },
      createOperationSpec,
      callback) as Promise<Models.ApiTokenAuthCreateResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const createOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "api-token-auth/",
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.JSONWebToken,
      required: true
    }
  },
  responses: {
    201: {
      bodyMapper: Mappers.JSONWebToken
    },
    default: {}
  },
  serializer
};
