/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/documentTypeOperationsMappers";
import * as Parameters from "../models/parameters";
import { ConcordiaApiContext } from "../concordiaApiContext";

/** Class representing a DocumentTypeOperations. */
export class DocumentTypeOperations {
  private readonly client: ConcordiaApiContext;

  /**
   * Create a DocumentTypeOperations.
   * @param {ConcordiaApiContext} client Reference to the service client.
   */
  constructor(client: ConcordiaApiContext) {
    this.client = client;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param [options] The optional parameters
   * @returns Promise<Models.DocumentTypeListResponse>
   */
  list(options?: msRest.RequestOptionsBase): Promise<Models.DocumentTypeListResponse>;
  /**
   * @param callback The callback
   */
  list(callback: msRest.ServiceCallback<Models.DocumentType[]>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  list(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DocumentType[]>): void;
  list(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DocumentType[]>, callback?: msRest.ServiceCallback<Models.DocumentType[]>): Promise<Models.DocumentTypeListResponse> {
    return this.client.sendOperationRequest(
      {
        options
      },
      listOperationSpec,
      callback) as Promise<Models.DocumentTypeListResponse>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param data
   * @param [options] The optional parameters
   * @returns Promise<Models.DocumentTypeCreateResponse>
   */
  create(data: Models.DocumentType, options?: msRest.RequestOptionsBase): Promise<Models.DocumentTypeCreateResponse>;
  /**
   * @param data
   * @param callback The callback
   */
  create(data: Models.DocumentType, callback: msRest.ServiceCallback<Models.DocumentType>): void;
  /**
   * @param data
   * @param options The optional parameters
   * @param callback The callback
   */
  create(data: Models.DocumentType, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DocumentType>): void;
  create(data: Models.DocumentType, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DocumentType>, callback?: msRest.ServiceCallback<Models.DocumentType>): Promise<Models.DocumentTypeCreateResponse> {
    return this.client.sendOperationRequest(
      {
        data,
        options
      },
      createOperationSpec,
      callback) as Promise<Models.DocumentTypeCreateResponse>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param id A unique integer value identifying this document type.
   * @param [options] The optional parameters
   * @returns Promise<Models.DocumentTypeReadResponse>
   */
  read(id: number, options?: msRest.RequestOptionsBase): Promise<Models.DocumentTypeReadResponse>;
  /**
   * @param id A unique integer value identifying this document type.
   * @param callback The callback
   */
  read(id: number, callback: msRest.ServiceCallback<Models.DocumentType>): void;
  /**
   * @param id A unique integer value identifying this document type.
   * @param options The optional parameters
   * @param callback The callback
   */
  read(id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DocumentType>): void;
  read(id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DocumentType>, callback?: msRest.ServiceCallback<Models.DocumentType>): Promise<Models.DocumentTypeReadResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      readOperationSpec,
      callback) as Promise<Models.DocumentTypeReadResponse>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param data
   * @param id A unique integer value identifying this document type.
   * @param [options] The optional parameters
   * @returns Promise<Models.DocumentTypeUpdateResponse>
   */
  update(data: Models.DocumentType, id: number, options?: msRest.RequestOptionsBase): Promise<Models.DocumentTypeUpdateResponse>;
  /**
   * @param data
   * @param id A unique integer value identifying this document type.
   * @param callback The callback
   */
  update(data: Models.DocumentType, id: number, callback: msRest.ServiceCallback<Models.DocumentType>): void;
  /**
   * @param data
   * @param id A unique integer value identifying this document type.
   * @param options The optional parameters
   * @param callback The callback
   */
  update(data: Models.DocumentType, id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DocumentType>): void;
  update(data: Models.DocumentType, id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DocumentType>, callback?: msRest.ServiceCallback<Models.DocumentType>): Promise<Models.DocumentTypeUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        data,
        id,
        options
      },
      updateOperationSpec,
      callback) as Promise<Models.DocumentTypeUpdateResponse>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param data
   * @param id A unique integer value identifying this document type.
   * @param [options] The optional parameters
   * @returns Promise<Models.DocumentTypeUpdate1Response>
   */
  update1(data: Models.DocumentType, id: number, options?: msRest.RequestOptionsBase): Promise<Models.DocumentTypeUpdate1Response>;
  /**
   * @param data
   * @param id A unique integer value identifying this document type.
   * @param callback The callback
   */
  update1(data: Models.DocumentType, id: number, callback: msRest.ServiceCallback<Models.DocumentType>): void;
  /**
   * @param data
   * @param id A unique integer value identifying this document type.
   * @param options The optional parameters
   * @param callback The callback
   */
  update1(data: Models.DocumentType, id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.DocumentType>): void;
  update1(data: Models.DocumentType, id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.DocumentType>, callback?: msRest.ServiceCallback<Models.DocumentType>): Promise<Models.DocumentTypeUpdate1Response> {
    return this.client.sendOperationRequest(
      {
        data,
        id,
        options
      },
      update1OperationSpec,
      callback) as Promise<Models.DocumentTypeUpdate1Response>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param id A unique integer value identifying this document type.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteMethod(id: number, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param id A unique integer value identifying this document type.
   * @param callback The callback
   */
  deleteMethod(id: number, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param id A unique integer value identifying this document type.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteMethod(id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      deleteMethodOperationSpec,
      callback);
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "document-type",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "DocumentType"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const createOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "document-type",
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.DocumentType,
      required: true
    }
  },
  responses: {
    201: {
      bodyMapper: Mappers.DocumentType
    },
    default: {}
  },
  serializer
};

const readOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "document-type/{id}/",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    200: {
      bodyMapper: Mappers.DocumentType
    },
    default: {}
  },
  serializer
};

const updateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "document-type/{id}/",
  urlParameters: [
    Parameters.id
  ],
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.DocumentType,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.DocumentType
    },
    default: {}
  },
  serializer
};

const update1OperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "document-type/{id}/",
  urlParameters: [
    Parameters.id
  ],
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.DocumentType,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.DocumentType
    },
    default: {}
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "document-type/{id}/",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    204: {},
    default: {}
  },
  serializer
};
