/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/procedureOperationsMappers";
import * as Parameters from "../models/parameters";
import { ConcordiaApiContext } from "../concordiaApiContext";

/** Class representing a ProcedureOperations. */
export class ProcedureOperations {
  private readonly client: ConcordiaApiContext;

  /**
   * Create a ProcedureOperations.
   * @param {ConcordiaApiContext} client Reference to the service client.
   */
  constructor(client: ConcordiaApiContext) {
    this.client = client;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param [options] The optional parameters
   * @returns Promise<Models.ProcedureListResponse>
   */
  list(options?: msRest.RequestOptionsBase): Promise<Models.ProcedureListResponse>;
  /**
   * @param callback The callback
   */
  list(callback: msRest.ServiceCallback<Models.Procedure[]>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  list(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Procedure[]>): void;
  list(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.Procedure[]>, callback?: msRest.ServiceCallback<Models.Procedure[]>): Promise<Models.ProcedureListResponse> {
    return this.client.sendOperationRequest(
      {
        options
      },
      listOperationSpec,
      callback) as Promise<Models.ProcedureListResponse>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param data
   * @param [options] The optional parameters
   * @returns Promise<Models.ProcedureCreateResponse>
   */
  create(data: Models.Procedure, options?: msRest.RequestOptionsBase): Promise<Models.ProcedureCreateResponse>;
  /**
   * @param data
   * @param callback The callback
   */
  create(data: Models.Procedure, callback: msRest.ServiceCallback<Models.Procedure>): void;
  /**
   * @param data
   * @param options The optional parameters
   * @param callback The callback
   */
  create(data: Models.Procedure, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Procedure>): void;
  create(data: Models.Procedure, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.Procedure>, callback?: msRest.ServiceCallback<Models.Procedure>): Promise<Models.ProcedureCreateResponse> {
    return this.client.sendOperationRequest(
      {
        data,
        options
      },
      createOperationSpec,
      callback) as Promise<Models.ProcedureCreateResponse>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param id A unique integer value identifying this procedure.
   * @param [options] The optional parameters
   * @returns Promise<Models.ProcedureReadResponse>
   */
  read(id: number, options?: msRest.RequestOptionsBase): Promise<Models.ProcedureReadResponse>;
  /**
   * @param id A unique integer value identifying this procedure.
   * @param callback The callback
   */
  read(id: number, callback: msRest.ServiceCallback<Models.Procedure>): void;
  /**
   * @param id A unique integer value identifying this procedure.
   * @param options The optional parameters
   * @param callback The callback
   */
  read(id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Procedure>): void;
  read(id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.Procedure>, callback?: msRest.ServiceCallback<Models.Procedure>): Promise<Models.ProcedureReadResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      readOperationSpec,
      callback) as Promise<Models.ProcedureReadResponse>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param data
   * @param id A unique integer value identifying this procedure.
   * @param [options] The optional parameters
   * @returns Promise<Models.ProcedureUpdateResponse>
   */
  update(data: Models.Procedure, id: number, options?: msRest.RequestOptionsBase): Promise<Models.ProcedureUpdateResponse>;
  /**
   * @param data
   * @param id A unique integer value identifying this procedure.
   * @param callback The callback
   */
  update(data: Models.Procedure, id: number, callback: msRest.ServiceCallback<Models.Procedure>): void;
  /**
   * @param data
   * @param id A unique integer value identifying this procedure.
   * @param options The optional parameters
   * @param callback The callback
   */
  update(data: Models.Procedure, id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Procedure>): void;
  update(data: Models.Procedure, id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.Procedure>, callback?: msRest.ServiceCallback<Models.Procedure>): Promise<Models.ProcedureUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        data,
        id,
        options
      },
      updateOperationSpec,
      callback) as Promise<Models.ProcedureUpdateResponse>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param data
   * @param id A unique integer value identifying this procedure.
   * @param [options] The optional parameters
   * @returns Promise<Models.ProcedureUpdate1Response>
   */
  update1(data: Models.Procedure, id: number, options?: msRest.RequestOptionsBase): Promise<Models.ProcedureUpdate1Response>;
  /**
   * @param data
   * @param id A unique integer value identifying this procedure.
   * @param callback The callback
   */
  update1(data: Models.Procedure, id: number, callback: msRest.ServiceCallback<Models.Procedure>): void;
  /**
   * @param data
   * @param id A unique integer value identifying this procedure.
   * @param options The optional parameters
   * @param callback The callback
   */
  update1(data: Models.Procedure, id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Procedure>): void;
  update1(data: Models.Procedure, id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.Procedure>, callback?: msRest.ServiceCallback<Models.Procedure>): Promise<Models.ProcedureUpdate1Response> {
    return this.client.sendOperationRequest(
      {
        data,
        id,
        options
      },
      update1OperationSpec,
      callback) as Promise<Models.ProcedureUpdate1Response>;
  }

  /**
   * This viewset automatically provides list and detail actions
   * @param id A unique integer value identifying this procedure.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteMethod(id: number, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param id A unique integer value identifying this procedure.
   * @param callback The callback
   */
  deleteMethod(id: number, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param id A unique integer value identifying this procedure.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteMethod(id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      deleteMethodOperationSpec,
      callback);
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "procedure/",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "Procedure"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const createOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "procedure/",
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.Procedure,
      required: true
    }
  },
  responses: {
    201: {
      bodyMapper: Mappers.Procedure
    },
    default: {}
  },
  serializer
};

const readOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "procedure/{id}/",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    200: {
      bodyMapper: Mappers.Procedure
    },
    default: {}
  },
  serializer
};

const updateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "procedure/{id}/",
  urlParameters: [
    Parameters.id
  ],
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.Procedure,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.Procedure
    },
    default: {}
  },
  serializer
};

const update1OperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "procedure/{id}/",
  urlParameters: [
    Parameters.id
  ],
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.Procedure,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.Procedure
    },
    default: {}
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "procedure/{id}/",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    204: {},
    default: {}
  },
  serializer
};
