/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/registerMappers";
import { ConcordiaApiContext } from "../concordiaApiContext";

/** Class representing a Register. */
export class Register {
  private readonly client: ConcordiaApiContext;

  /**
   * Create a Register.
   * @param {ConcordiaApiContext} client Reference to the service client.
   */
  constructor(client: ConcordiaApiContext) {
    this.client = client;
  }

  /**
   * @param data
   * @param [options] The optional parameters
   * @returns Promise<Models.RegisterCreateResponse>
   */
  create(data: Models.Person, options?: msRest.RequestOptionsBase): Promise<Models.RegisterCreateResponse>;
  /**
   * @param data
   * @param callback The callback
   */
  create(data: Models.Person, callback: msRest.ServiceCallback<Models.Person>): void;
  /**
   * @param data
   * @param options The optional parameters
   * @param callback The callback
   */
  create(data: Models.Person, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.Person>): void;
  create(data: Models.Person, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.Person>, callback?: msRest.ServiceCallback<Models.Person>): Promise<Models.RegisterCreateResponse> {
    return this.client.sendOperationRequest(
      {
        data,
        options
      },
      createOperationSpec,
      callback) as Promise<Models.RegisterCreateResponse>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const createOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "register",
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.Person,
      required: true
    }
  },
  responses: {
    201: {
      bodyMapper: Mappers.Person
    },
    default: {}
  },
  serializer
};
