/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/userOperationsMappers";
import * as Parameters from "../models/parameters";
import { ConcordiaApiContext } from "../concordiaApiContext";

/** Class representing a UserOperations. */
export class UserOperations {
  private readonly client: ConcordiaApiContext;

  /**
   * Create a UserOperations.
   * @param {ConcordiaApiContext} client Reference to the service client.
   */
  constructor(client: ConcordiaApiContext) {
    this.client = client;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.UserListResponse>
   */
  list(options?: msRest.RequestOptionsBase): Promise<Models.UserListResponse>;
  /**
   * @param callback The callback
   */
  list(callback: msRest.ServiceCallback<Models.UserList[]>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  list(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.UserList[]>): void;
  list(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.UserList[]>, callback?: msRest.ServiceCallback<Models.UserList[]>): Promise<Models.UserListResponse> {
    return this.client.sendOperationRequest(
      {
        options
      },
      listOperationSpec,
      callback) as Promise<Models.UserListResponse>;
  }

  /**
   * @param data
   * @param [options] The optional parameters
   * @returns Promise<Models.UserCreateResponse>
   */
  create(data: Models.UserList, options?: msRest.RequestOptionsBase): Promise<Models.UserCreateResponse>;
  /**
   * @param data
   * @param callback The callback
   */
  create(data: Models.UserList, callback: msRest.ServiceCallback<Models.UserList>): void;
  /**
   * @param data
   * @param options The optional parameters
   * @param callback The callback
   */
  create(data: Models.UserList, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.UserList>): void;
  create(data: Models.UserList, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.UserList>, callback?: msRest.ServiceCallback<Models.UserList>): Promise<Models.UserCreateResponse> {
    return this.client.sendOperationRequest(
      {
        data,
        options
      },
      createOperationSpec,
      callback) as Promise<Models.UserCreateResponse>;
  }

  /**
   * @param id A unique integer value identifying this usuario.
   * @param [options] The optional parameters
   * @returns Promise<Models.UserReadResponse>
   */
  read(id: number, options?: msRest.RequestOptionsBase): Promise<Models.UserReadResponse>;
  /**
   * @param id A unique integer value identifying this usuario.
   * @param callback The callback
   */
  read(id: number, callback: msRest.ServiceCallback<Models.UserList>): void;
  /**
   * @param id A unique integer value identifying this usuario.
   * @param options The optional parameters
   * @param callback The callback
   */
  read(id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.UserList>): void;
  read(id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.UserList>, callback?: msRest.ServiceCallback<Models.UserList>): Promise<Models.UserReadResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      readOperationSpec,
      callback) as Promise<Models.UserReadResponse>;
  }

  /**
   * @param data
   * @param id A unique integer value identifying this usuario.
   * @param [options] The optional parameters
   * @returns Promise<Models.UserUpdateResponse>
   */
  update(data: Models.UserList, id: number, options?: msRest.RequestOptionsBase): Promise<Models.UserUpdateResponse>;
  /**
   * @param data
   * @param id A unique integer value identifying this usuario.
   * @param callback The callback
   */
  update(data: Models.UserList, id: number, callback: msRest.ServiceCallback<Models.UserList>): void;
  /**
   * @param data
   * @param id A unique integer value identifying this usuario.
   * @param options The optional parameters
   * @param callback The callback
   */
  update(data: Models.UserList, id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.UserList>): void;
  update(data: Models.UserList, id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.UserList>, callback?: msRest.ServiceCallback<Models.UserList>): Promise<Models.UserUpdateResponse> {
    return this.client.sendOperationRequest(
      {
        data,
        id,
        options
      },
      updateOperationSpec,
      callback) as Promise<Models.UserUpdateResponse>;
  }

  /**
   * @param data
   * @param id A unique integer value identifying this usuario.
   * @param [options] The optional parameters
   * @returns Promise<Models.UserUpdate1Response>
   */
  update1(data: Models.UserList, id: number, options?: msRest.RequestOptionsBase): Promise<Models.UserUpdate1Response>;
  /**
   * @param data
   * @param id A unique integer value identifying this usuario.
   * @param callback The callback
   */
  update1(data: Models.UserList, id: number, callback: msRest.ServiceCallback<Models.UserList>): void;
  /**
   * @param data
   * @param id A unique integer value identifying this usuario.
   * @param options The optional parameters
   * @param callback The callback
   */
  update1(data: Models.UserList, id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<Models.UserList>): void;
  update1(data: Models.UserList, id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<Models.UserList>, callback?: msRest.ServiceCallback<Models.UserList>): Promise<Models.UserUpdate1Response> {
    return this.client.sendOperationRequest(
      {
        data,
        id,
        options
      },
      update1OperationSpec,
      callback) as Promise<Models.UserUpdate1Response>;
  }

  /**
   * @param id A unique integer value identifying this usuario.
   * @param [options] The optional parameters
   * @returns Promise<msRest.RestResponse>
   */
  deleteMethod(id: number, options?: msRest.RequestOptionsBase): Promise<msRest.RestResponse>;
  /**
   * @param id A unique integer value identifying this usuario.
   * @param callback The callback
   */
  deleteMethod(id: number, callback: msRest.ServiceCallback<void>): void;
  /**
   * @param id A unique integer value identifying this usuario.
   * @param options The optional parameters
   * @param callback The callback
   */
  deleteMethod(id: number, options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<void>): void;
  deleteMethod(id: number, options?: msRest.RequestOptionsBase | msRest.ServiceCallback<void>, callback?: msRest.ServiceCallback<void>): Promise<msRest.RestResponse> {
    return this.client.sendOperationRequest(
      {
        id,
        options
      },
      deleteMethodOperationSpec,
      callback);
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const listOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "user/",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Sequence",
          element: {
            type: {
              name: "Composite",
              className: "UserList"
            }
          }
        }
      }
    },
    default: {}
  },
  serializer
};

const createOperationSpec: msRest.OperationSpec = {
  httpMethod: "POST",
  path: "user/",
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.UserList,
      required: true
    }
  },
  responses: {
    201: {
      bodyMapper: Mappers.UserList
    },
    default: {}
  },
  serializer
};

const readOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "user/{id}/",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    200: {
      bodyMapper: Mappers.UserList
    },
    default: {}
  },
  serializer
};

const updateOperationSpec: msRest.OperationSpec = {
  httpMethod: "PUT",
  path: "user/{id}/",
  urlParameters: [
    Parameters.id
  ],
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.UserList,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.UserList
    },
    default: {}
  },
  serializer
};

const update1OperationSpec: msRest.OperationSpec = {
  httpMethod: "PATCH",
  path: "user/{id}/",
  urlParameters: [
    Parameters.id
  ],
  requestBody: {
    parameterPath: "data",
    mapper: {
      ...Mappers.UserList,
      required: true
    }
  },
  responses: {
    200: {
      bodyMapper: Mappers.UserList
    },
    default: {}
  },
  serializer
};

const deleteMethodOperationSpec: msRest.OperationSpec = {
  httpMethod: "DELETE",
  path: "user/{id}/",
  urlParameters: [
    Parameters.id
  ],
  responses: {
    204: {},
    default: {}
  },
  serializer
};
